
[general]
static=yes
writeprotect=no

[confirmacion-citas]
exten => s,1,Answer()
exten => s,n,AGI(confirmacion.py)
exten => s,n,Hangup()

exten => 1002,1,Dial(PJSIP/1002,30)
exten => 1002,n,Hangup()

exten => 9000,1,Answer()
exten => 9000,n,AGI(confirmacion.py)
exten => 9000,n,Hangup()

exten => 1001,1,Dial(PJSIP/1001,30)
exten => 1001,n,Hangup()
