[1001]
type=endpoint
context=confirmacion-citas
disallow=all
allow=ulaw
auth=auth1001
aors=1001
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[auth1001]
type=auth
auth_type=userpass
username=1001
password=CAMBIAR_PASSWORD

[1001]
type=aor
max_contacts=1
remove_existing=yes

[1002]
type=endpoint
context=confirmacion-citas
disallow=all
allow=ulaw
auth=auth1002
aors=1002
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[auth1002]
type=auth
auth_type=userpass
username=1002
password=CAMBIAR_PASSWORD

[1002]
type=aor
max_contacts=1
remove_existing=yes
